// import vazirFont from "@/constants/localFont";
// import "@/styles/globals.css";
// import { Toaster } from "react-hot-toast";

import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="dark-mode">
      <body className={`min-h-screen font-sans `}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
